### ISSUE TITLE
ValueError: Illegal backbone or feature shape. Expected output for an image is a 1-dim tensor.

### ISSUE THREAD

**Issue by Hengrui-Gu** [sicara/easy-few-shot-learning#133]
Firstly, thanks for your great work! 
**Problem**
I follow the **episodic_training.ipynb** and successfully run the prototypical network with resnet12 on CUB-200 dataset. But when i simply changed the  prototypical network to matching network in the script (i set the feature_dimension to **64** and keep the support/query encoder as **None**), the value error happened. 

**How can we help**
Could you please provide some detailed tutorials about matching network? Especially about input format and which function should be used to conduct few-shot episodic_training for matching network. Thanks again and look forward to your early reply !

**Comment by ebennequin** [comment]
Hi! Which resnet12 are you using? This error indicates that your backbone doesn't output a 1-dimensional tensor. Can you check the output dimension of your backbone?

I will of course help you with your issue but I don't plan on producing any more content for Matching Networks because:

- they are deprecated, far from SOTA and therefore not included in the benchmarks of the majority of recent works;
- there are no publicly available weights for the feature encoders.
