### ISSUE TITLE
Cannot import and download the CUB dataset on episodic_training

### ISSUE THREAD

**Issue by DickHanselRyan** [sicara/easy-few-shot-learning#136]
**Problem**
I run the episodic_training on my own local computer's jupyter notebook and it shows this issue when I run the !make download-cub
![image](https://github.com/sicara/easy-few-shot-learning/assets/83385410/d9b54361-cefc-4f4d-8013-7c8ab234e81e)
![image](https://github.com/sicara/easy-few-shot-learning/assets/83385410/7831e825-4d26-4114-8850-e2e28e65b832)

**How can we help**
Do I need to install extensions, change the code, or anything else? Thank you

**Comment by ebennequin** [comment]
It seems that you are trying to use the `make` command on Windows without having "make" installed. Shell commands in the notebooks are meant for unix-like operating systems. I suggest you adapt these commands to your OS.

In the future I would be grateful if you could:

1. [research standard errors on Google](https://www.google.com/search?q=%27make%27+is+not+recognized+as+an+internal+or+external+command%2C+operable+program+or+bash+file&oq=%27make%27+is+not+recognized+as+an+internal+or+external+command%2C+operable+program+or+bash+file&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDcyMTNqMGo0qAIAsAIA&sourceid=chrome&ie=UTF-8) before raising an issue;
2. copy/paste your stack trace instead of sharing a screenshot.

**Comment by deemoe404** [comment]
Try adding `%cd ..` above.

**Comment by YiDanCheung** [comment]
> **Problem** I run the episodic_training on my own local computer's jupyter notebook and it shows this issue when I run the !make download-cub ![image](https://private-user-images.githubusercontent.com/83385410/306934208-d9b54361-cefc-4f4d-8013-7c8ab234e81e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzA3ODgsIm5iZiI6MTcwOTYzMDQ4OCwicGF0aCI6Ii84MzM4NTQxMC8zMDY5MzQyMDgtZDliNTQzNjEtY2VmYy00ZjRkLTgwMTMtN2M4YWIyMzRlODFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5MjEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMmE4MDA0OTMyNjYyYTZkMzY2YWE1MzI3ZjEzZmE4YjJiYjhmY2FkYTM4MjdiNjZkNGYyYWQ2NGIwNjg0MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xZJZ6jIeC9llyf_9MHOmfao_I-JiR1k6T_uF0WD_fH8) ![image](https://private-user-images.githubusercontent.com/83385410/306934289-7831e825-4d26-4114-8850-e2e28e65b832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzA3ODgsIm5iZiI6MTcwOTYzMDQ4OCwicGF0aCI6Ii84MzM4NTQxMC8zMDY5MzQyODktNzgzMWU4MjUtNGQyNi00MTE0LTg4NTAtZTJlMjhlNjViODMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5MjEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2OTMzYjJmODkyMjNiZThlMjQzZGQ3MjEyNTg0YTA4M2MxNGU3M2U3Y2M4YTJiMjA0NGFlNGVlNjk3NWIxZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IYmQqNAh5CANexX7eZlP1FXBUZRpubXRZHYucrz3_h8)
> 
> **How can we help** Do I need to install extensions, change the code, or anything else? Thank you

you can download with this Google Drive link [CUB](https://drive.usercontent.google.com/download?id=1GDr1OkoXdhaXWGA8S3MAq3a522Tak-nx&export=download)
