### ISSUE TITLE
Loss in Episodical training

### ISSUE THREAD

**Issue by charurathour** [sicara/easy-few-shot-learning#155]
In episodical training shouldn't the weights be upgraded according to average loss over all episodes instead of updating weights according to loss of every episode?

**Comment by ebennequin** [comment]
It is common practice in deep learning to update the weights after each batch of images rather than at the end of the epoch. In episodical training, the batches are called episodes. In the same fashion, we update the weights after each episode.

You can implement a mechanism to only update the weights every N episodes, but I am unsure it will improve your training's efficiency.
