### ISSUE TITLE
Improvement of TIM

### ISSUE THREAD

**Issue by PierreColombo** [sicara/easy-few-shot-learning#38]
Hi !

Thanks a lot for your great work. Is it possible to add the improvement of TIM  https://proceedings.neurips.cc/paper/2021/file/4d7a968bb636e25818ff2a3941db08c1-Paper.pdf ? 

Kindest regards,
Pierre

**Comment by ebennequin** [comment]
Hi Pierre, I'm glad to see that you're using EasyFSL!

I don't have an up-and-ready implementation of TIM with alpha-divergences, but I agree it would be a great addition to the library. As I understand it from [the original code](https://github.com/oveilleux/Realistic_Transductive_Few_Shot/blob/master/src/methods/tim.py), the only difference is in the computation of the 3 entropies, so I think a straightforward implementation could be

- a `Alpha_TIM` class extending `TIM`
- we put each entropy computation in a separate method of `TIM`
- Alpha_TIM just overwrites these methods using a `self.alpha_{cross,marginal,conditional}` field

If you have time and want to add it to EasyFSL, I would love to help you! Otherwise, I'll implement it when I have some time and add it to the next release :smile:
