### ISSUE TITLE
KeyError with tensor input in MiniImageNet.__get_item__() 

### ISSUE THREAD

**Issue by egarcol** [sicara/easy-few-shot-learning#41]
**Problem**
I'm trying to modify and run the _my_first_few_shot_classifier_ notebook with the miniImageNet data set. 
But not sure about the data (where to get it/how to store it/how to load it). 

What is the recommended/correct/required form ? I have downloaded various (mini) imagenet data sets and each are quite different.

(1) All images (60k) are in a single directory (/images) with the naming format:  
**n0153282900000005.jpg**

(2) Test images are in one test directory & train/val are in a directory p/class.

test-2015 / ILSVRC2015 / Data / DET / test
**ILSVRC2012_test_00000003.JPEG**

train-val-2015 / ILSVRC2015 / Data / DET / train / ILSVRC2013_train / n00007846
**n00007846_71814.JPEG**

(3) No images but a python dict with the (I'm guessing) RGB values of each image.
```
{'image_data': array([[[[200, 242, 240],
         [204, 235, 249],
         [202, 235, 250],
         ...,
         [210, 222, 238],
         [206, 219, 232],
         [218, 229, 237]],
        [[167, 171, 219],
         [172, 176, 224],
         [175, 179, 227],
         ...,
         [ 68,  74,  74],
         [ 47,  53,  53],
         [ 80,  85,  91]]]], dtype=uint8), 'class_dict': {'n01930112': [0, 1, 2, 3, 4
```

I got 1 from a Google drive. I got 2 from official imagenet ILSVRC2015 download page. And the last one from Kaggle.

**Considered solutions**
I will show what I have tried re data set number 1 (where all images are in a single directory).

```
base = "\images"
train_set = MiniImageNet(root=base, split="train", training=True) 
test_set = MiniImageNet(root=base, split="test", training=False)
```

And also tried:

```
train_set = MiniImageNet(
    split="train",
    root=base,
    transform=transforms.Compose(
        [
            transforms.Grayscale(num_output_channels=3),
            transforms.RandomResizedCrop(image_size),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
        ]
    ),
)
```

But in both cases, getting error.

```
Traceback (most recent call last):
  File "C:/git_repos/dcu/fsl/easy-few-shot-learning/gary-code/first-fsl-orig.py", line 172, in <module>
    ) = next(iter(test_loader))
  File "C:\git_repos\dcu\fsl\easy-few-shot-learning\venv\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\git_repos\dcu\fsl\easy-few-shot-learning\venv\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\git_repos\dcu\fsl\easy-few-shot-learning\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\git_repos\dcu\fsl\easy-few-shot-learning\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\git_repos\dcu\fsl\easy-few-shot-learning\easyfsl\datasets\mini_imagenet.py", line 110, in __getitem__
    Image.open(self.data_df.image_path[item]).convert("RGB")
  File "C:\git_repos\dcu\fsl\easy-few-shot-learning\venv\lib\site-packages\pandas\core\series.py", line 882, in __getitem__
    return self._get_value(key)
  File "C:\git_repos\dcu\fsl\easy-few-shot-learning\venv\lib\site-packages\pandas\core\series.py", line 990, in _get_value
    **loc = self.index.get_loc(label)**
  File "C:\git_repos\dcu\fsl\easy-few-shot-learning\venv\lib\site-packages\pandas\core\indexes\range.py", line 358, in get_loc
    raise KeyError(key)
KeyError: tensor(9552)

Process finished with exit code 1
```

It looks like there are no labels assigned to the images.

**How can we help**
So the 2 questions are:
(1) What is the correct way to store the data ?
(2) How to load the data ?

Any help will be much appreciated. An example of this notebook running on mini imagenet would be most helpful.

Thanks, 

Gary

**Comment by ebennequin** [comment]
Hi @egarcol and thank you for using EasyFSL, and also for the very clear problem statement! Let's look at [the MiniImageNet class](https://github.com/sicara/easy-few-shot-learning/blob/master/easyfsl/datasets/mini_imagenet.py).

### `specs_file` or `split`

To define the images used, the constructor needs a CSV specs_file like [this one](https://github.com/sicara/easy-few-shot-learning/blob/master/data/mini_imagenet/test.csv). You can also, as you've done in your examples, just define the split, in which case it will look for a file named `data/mini_imagenet/{split}.csv` (see [here](https://github.com/sicara/easy-few-shot-learning/blob/a770d9a318b72e19d2e81ba86c63f539a2f2ddcc/easyfsl/datasets/mini_imagenet.py#L141)), so you must ensure the file is there, or specify the path to the file with the `specs_file` argument if it's somewhere else.

### `MiniImageNet` expects images with path `root/class_name/image_name`

This corresponds to the second shape that you described. You can see that the constructor will build for each instance an image path like this: 

```python
        return pd.read_csv(specs_file).assign(
            image_path=lambda df: df.apply(
                lambda row: self.root / row["class_name"] / row["image_name"], axis=1
            )
        )
```

And this image path is where the `__get_item__` method will look for the image.

### There is an abstract `FewShotDataset` class that you can extend for all your dataset needs

While the built-in `MiniImageNet` class puts restrictions on the shape of your data source, you can basically make any data source work with EasyFSL by creating your own extension of `FewShotDataset`. It won't be as easy though.

-------------

But none of this is what's causing your problem. The problem seems to be that `MiniImageNet.__get_item__()` takes `tensor(9552)` and not `9552` as input (which is often the case when using `DataLoader`), so it will look for the key `tensor(9552)` in the index of the `self.data_df` data frame. While `9552` is a valid key, `tensor(9552)` is not, hence the bug.

I'm sorry I left this error in the code. A quick fix should be to create a `self.images` list in the constructor using `self.data_df.image_path` and using this list in `__get_item__`.

I'm marking this as a bug and will release the fix next week.
